config/routes.rb
Rails.application.routes.draw do

  resources :welcomes do
    member do
      post :find
    end
  end

  get 'search/:search_word' => 'search#show' , as: :search
  
  

  root to: 'welcomes#home'
  get 'help', to: 'help#home'
  get 'player_signup', to: 'players#new'
  get 'trainer_signup', to: 'trainers#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :welcomes, only: [:home, :find]
  resources :users
  resources :players
  resources :trainers
  resources :sessions, only: [:new, :create, :destroy]
  resources :training_contents
  resources :relationships, only: [:create, :destroy]

end

app/models/training_content.rb
class TrainingContent < ActiveRecord::Base
  belongs_to :trainer
  mount_uploader :image, ImageUploader
  
  validates :name, presence: true
  validates :content, presence: true
  validates :sports_type, presence: true
  
end

app/controllers/training_contents_controller.rb
class TrainingContentsController < ApplicationController
    before_action :logged_in_user, only: [:new, :create, :destroy, :edit, :update]
    before_action :set_training_content, only: [:show, :edit, :update]
   
   def show
   end  
   
   def new
     @training_content = TrainingContent.new       
   end
  
    def create
        @training_content = current_user.training_contents.build(training_content_params)
        if @training_content.save
            flash[:success] = "プランを作成しました！"
            redirect_to root_url
        else
            render 'welcomes/home'
        end    
    end
    
    def edit
    @training_content = current_user.training_contents.find_by(id: params[:id])
    end
 
    def update
    @training_content = current_user.training_contents.find_by(id: params[:id])    
    if @training_content.update(training_content_params)
    flash[:success] = "プランを編集しました。"
    redirect_to request.referrer || root_url
    else
        render 'edit'
    end    
    end
   

   
    
    def destroy
    @training_content = current_user.training_contents.find_by(id: params[:id])
    return redirect_to root_url if @training_content.nil?
    @training_content.destroy
    flash[:success] = "プランを消去しました。"
    redirect_to request.referrer || root_url
    end
    

    
    private
    def training_content_params
    params.require(:training_content).permit(:name, :content,  
                        :sports_type, :purpose, :lengths, :image)
    end
    
    
    def set_training_content
    @training_content = TrainingContent.find(params[:id])
  end
end

app/views/training_contents/_list.html.erb
<div id ="list">
<h2>トレーニングプラン一覧</h2>
     
<% @training_contents.each do |training_content| %>

<div class = "training_content_list">
<p class="list_image">
     <% if training_content.image.present? %>
     <%= image_tag training_content.image.url %>
     <% end %>
</p>     
     
<h4 id ="list_name"><%= link_to training_content.name, training_content %></h4>
<h5 id ="trainer_name"><%= training_content.trainer.name %></h5>

</div>

<% end %>
</div>

app/views/training_contents/_training_content.html.erb
<div class ="trainer_training_content">
<h3>・<%= training_content.name %><h3>
  
<%= link_to "詳細" , training_content, class: "btn btn-info btn-sm" %>

<% if current_user == training_content.trainer %>
      <%= link_to "[edit]" , edit_training_content_path(training_content) %>
      
      <%= link_to "[delete]", training_content, method: :delete,
                                       data: { confirm: "You sure?" } %>
<% end %>
</div>

app/views/training_contents/_training_contents.html.erb
<div id ="list">
<% @training_contents.each do |training_content| %>

<div class = "training_content_list">
<p class="list_image">
     <% if training_content.image.present? %>
     <%= image_tag training_content.image.url %>
     <% end %>
</p>     
     
<h4 id ="list_name"><%= link_to training_content.name, training_content %></h4>
<h5 id ="trainer_name"><%= training_content.trainer.name %></h5>

</div>

<% end %>
</div>

app/views/training_contents/edit.html.erb
<h1>トレーニングプラン編集</h1>

<%= render 'shared/training_content_form' %>

app/views/training_contents/new.html.erb
<h1>トレーニングプラン作成</h1>

<% if current_user.training_contents.count >= 3 %>
    <div>3つ以上登録できません。</div>
<% else %>
   <%= render 'shared/training_content_form'%>
   
<% end %>

app/views/training_contents/show.html.erb
<h1>トレーニングプラン詳細</h1>

<div id ="training_content_background">

<div class ="training_content_box">

 <div id ="training_content_top">
 <p id ="training_content_purpose">
 <%= @training_content.purpose %>
 </p>
    
 <h2>
 <%= @training_content.name %>
 </h2>

 <div id="detail_image">
     <% if @training_content.image.present? %>
     <%= image_tag @training_content.image.url %>
     <% end %>
 </div>
 
 </div>

     <div id ="detail_content">
     <h2>こんな内容です</h2>
     <p>
     <%= @training_content.content %>
     </p>
     </div>

     <div id ="content_info">
     <p><%= @training_content.sports_type %></p>
     <p><%= @training_content.lengths%></p>
     <p><%= @training_content.price %></p>
     </div>


     <div class="trainer_info">
     <h2>担当するトレーナー</h2>
     <div class ="box1">
     <p><%= gravatar_for @training_content.trainer, size: 130 %></p>
     </div>
     
     <div class ="box2">
     <p><%= @training_content.trainer.name %></p>
     <p><%= @training_content.trainer.profile %></p>
     
     <p><%= @training_content.trainer.speciality %></p>
     <p><%= @training_content.trainer.sports_type %></p>
     
     </div>
     
     </div>
     
</div>
</div>