config/routes.rb
Rails.application.routes.draw do

  resources :welcomes do
    member do
      post :find
    end
  end

  get 'search/:search_word' => 'search#show' , as: :search
  
  

  root to: 'welcomes#home'
  get 'help', to: 'help#home'
  get 'player_signup', to: 'players#new'
  get 'trainer_signup', to: 'trainers#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :welcomes, only: [:home, :find]
  resources :users
  resources :players
  resources :trainers
  resources :sessions, only: [:new, :create, :destroy]
  resources :training_contents
  resources :relationships, only: [:create, :destroy]

end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  before_action :logged_in_user, except: [:find]
  
  
  def home
    
    #トップ画面にプランを表示する
     @training_contents = TrainingContent.all
     
     
    # トレーナーだったら
    # if current_user.instance_of? Trainer
    # if current_user.instace_of? Player
   
    # if params[:type] == "Player"
    if current_user.instance_of? Player
      @player = current_user
      #@training_content = trainer.training_contents
    end  
    
    if current_user.instance_of? Trainer
      @training_content = current_user.training_contents.build if logged_in?
    end
  
  end
  
  def find
    if logged_in?
      
      if request.post? then
        fstr = params[:fstr]
        @training_contents = TrainingContent.where("name like ?","%"+ fstr + "%")
        # @training_contents = TrainingContent.where("content like ?","%"+ fstr + "%")
        # @training_contents = TrainingContent.where("sports_type like ?","%"+ fstr + "%")
        # @training_contents = TrainingContent.where("purpose like ?","%"+ fstr + "%")
      end
    end
  end  
  
  
  private
  def set_training_content
    @training_content = TrainingContent.find(params[:id])
  end
  
end

app/views/welcomes/_find.html.erb
<% if logged_in? %>
<div class="search">
    <%= form_tag find_welcome_path(current_user), method: :post do %>
    <%= text_field_tag :fstr , params[:fstr], class: "form-control", placeholder: "キーワードを入力", required: true %>
    <%= submit_tag "プランを探す", name: nil , class: "btn btn-success", data: { disable_with: "検索中..."} %>
    <% end %>
</div>
<div class="clear"></div>


<% end %>

app/views/welcomes/find.html.erb
<%= render 'shared/cover' %>

<h1>検索結果</h1>

<div class="col-md-3">
        
        <%= render 'welcomes/find' %>
        <br>
        <h4>カテゴリーから探す</h4>
        <%= render 'shared/category_search' %>
</div>

<div class="search-result">
  <% if @training_contents.present? %>
  
    <%= render 'training_contents/training_contents', training_contents: @training_contents %>
    
  <% elsif params[:fstr].present? %>
   <div id ="alert">
    <div class="alert alert-danger">
      <span class="glyphicon glyphicon-remove-sign" aria-hidden="true"></span>
      検索したプランはありません
    </div>
    </div>
  <% end %>
</div>

app/views/welcomes/home.html.erb
<%= render 'shared/cover' %>


<% if logged_in? %>
<%= render 'find' %>

<%= render 'training_contents/list'  %>
<% end %>