config/routes.rb
Rails.application.routes.draw do

  resources :welcomes do
    member do
      post :find
    end
  end

  get 'search/:search_word' => 'search#show' , as: :search
  
  

  root to: 'welcomes#home'
  get 'help', to: 'help#home'
  get 'player_signup', to: 'players#new'
  get 'trainer_signup', to: 'trainers#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :welcomes, only: [:home, :find]
  resources :users
  resources :players
  resources :trainers
  resources :sessions, only: [:new, :create, :destroy]
  resources :training_contents
  resources :relationships, only: [:create, :destroy]

end

app/views/layouts/_footer.html.erb
<footer>
  <div class="copyright">© <%= Date.today.year %> SportsHub.</div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "SportsHub", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if logged_in? %>
          
          
          <li>
            <% if current_user.instance_of? Trainer %>
            <%= link_to "Plan Create", new_training_content_path %>
             <% end %>      
          </li>
         
          
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              
              
              <li>
                <% if current_user.instance_of? Trainer %>
                <%= link_to "Settings", edit_trainer_path(current_user) %>
                <% end %>
              </li>
              
              <li>
                <% if current_user.instance_of? Player %>
                <%= link_to "Settings", edit_player_path(current_user) %>
                <% end %>
              </li> 
              
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sportshub</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<div class ="container">
  <% flash.each do |message_type, message| %> 
      <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
<%= yield %>
</div>
<%= render 'layouts/footer' %>
</body>
</html>